### ISSUE TITLE
WEBSITE_PORT variable not respected in api calls

### ISSUE THREAD

**Issue by Charlie-Root** [pommee/goaway#12]
When setting WEBSITE_PORT to 8090, API calls still go to 8080 causing cors issues.

**Comment by pommee** [comment]
Thanks for reporting, having a look.

**Comment by pommee** [comment]
This should now be fixed, please update to the latest version 0.48.7 and verify.

**Comment by Charlie-Root** [comment]
Most pages now indeed work, Upstreams and Clients still throw the error (even tho the port seems to be correct).

**Comment by pommee** [comment]
Thanks for reporting, this has now been fixed in [v0.48.8](https://github.com/pommee/goaway/releases/tag/v0.48.8).  

Please verify and close the issue if it solved your problem.

**Comment by Charlie-Root** [comment]
Works!
