### ISSUE TITLE
Updating the version via GUI reverts password to the one generated in log

### ISSUE THREAD

**Issue by BackedUpBooty** [pommee/goaway#24]
**Describe the bug**
Password changed in GUI gets overwritten on version update

**To Reproduce**
1. Install using docker (in this instance on a proxmox LXC)
2. Sign in using the provided password generated in the logs
3. Go to settings and change the password
4. Click 'update' when notified in the GUI of a new version
5. At some point the login token expires
6. Attempt to log in with chosen password
7. Fail
8. Search logs, find the generated password, use that
9. Succeed

There are no supporting logs in this. The only log messages which appear are if the user is not recognized, not the password being incorrect.

**Comment by BackedUpBooty** [comment]
Some more strange behaviour. Today I did a fresh install, left it for a while. Didn't make any changes at all (no additional lists, no password change). After a few hours it had logged out, and now won't allow me to log in with the original credentials.

**Comment by pommee** [comment]
This sounds very odd. I have only let it sit until logout a couple of times, but then the login process works as it should with the latest password. Neither do I see how the update process would affect the state.  

> After a few hours it had logged out, and now won't allow me to log in with the original credentials.

Does it allow you to login with the latest password in this case?

Will take a look at this when I have some spare time over. Might need to add some more debug logs to make the investigation easier.

**Comment by BackedUpBooty** [comment]
Sorry for the late reply.

> 
> > After a few hours it had logged out, and now won't allow me to log in with the original credentials.
> 
> Does it allow you to login with the latest password in this case?

Yes it does. But as per my later comment, I did a fresh install (didn't go ahead and add all my lists this time) and made no changes at all to access credentials. After X amount of time it logged me out, and then wouldn't log in at all with the same password.

I've tested it on 3 different types of system (Proxmox Ubuntu VM, Proxmox LXC, Synology NAS) and it's done the same for me every time. Using the compose or the run command makes no difference. 

Normally I'd think this was my fault / I'm doing something wrong, but agreed that some additional logging would be helpful here.

**Comment by pommee** [comment]
@BackedUpBooty Sorry for not completely understanding the picture here. Let's break it down.

1. Fresh install
2. Log in
3. No password change (i.e still supposed to use the generated one going forward)
4. Logged out after X amount of time
5. Can't login with the generated password

Is this correct?

**Comment by BackedUpBooty** [comment]
@pommee yes exactly right. sorry for the delay, I decided to create a fresh instance in a fresh LXC again just in case, and that's what I'm experiencing. I get the little modal popup bottom right which says 'Warning Invalid Credentials'.

**Comment by pommee** [comment]
I am interested to know if the generated password is stored in your `user` table after this occurs.  
It should look something similar to: `$2a$10$Y8Rny3g5z....Y8Rny3g5z...`.  

**Please do not share the full value as it is a password**

**Comment by BackedUpBooty** [comment]
> I am interested to know if the generated password is stored in your `user` table after this occurs

Where can I find the user table?

**Comment by pommee** [comment]
It is stored in the database file, located at "./data/database.db".

**Comment by BackedUpBooty** [comment]
![Image](https://github.com/user-attachments/assets/ce3992b0-0bb4-4b21-8565-91b11f8110f4)

To be honest I'm not sure I'm looking in the right place, but this is the only place I can find 'password' written that isn't to do with one of the lists I set it to use. 

EDIT: Ok I should have checked the logs first. So this time it didn't display the same behaviour for a day, and then not until I restarted the VM. It looks like the password has been changed as none of the data persisted. I don't know why this would be the case, no other containers have an issue when restarting. 

my compose is as follows, it's on a debian VM in proxmox.

```
goaway:
    image: pommee/goaway:latest
    container_name: goaway
    build: .
    volumes:
      - goaway_data:/home/appuser
    environment:
      - DNS_PORT=${DNS_PORT:-53}
      - WEBSITE_PORT=${WEBSITE_PORT:-8080}
    ports:
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/udp"
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/tcp"
      - "${WEBSITE_PORT:-8080}:${WEBSITE_PORT:-8080}/tcp"
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW

volumes:
  goaway_data:
    name: goaway_data
```

**Comment by pommee** [comment]
@BackedUpBooty The database file stems from SQLite, meaning you need to query the table.  
You can run something like this to get the password:  

```shell
# <path-to-db> will most likely be ./data/database.db
sqlite3 <path-to-db> "SELECT password FROM user"
```

**Comment by pommee** [comment]
> EDIT: Ok I should have checked the logs first. So this time it didn't display the same behaviour for a day, and then not until I restarted the VM. It looks like the password has been changed as none of the data persisted. I don't know why this would be the case, no other containers have an issue when restarting.
> ...

I am interested to know if this might be related to you mounting `/home/appuser` inside the container. This was changed recently (after this was reported so might not be related). However if you look at the updated README section [Using Docker Compose](https://github.com/pommee/goaway?tab=readme-ov-file#option-1-docker-installation-recommended:~:text=Using%20Docker%20Compose) you will find that now it will use:
* `/app/data`
* `/app/config`  

A few recommendations:
* Alter the persisting volume mounting point
* Run a fresh install with no persisting volumes
* Mount host dirs and run the command provided above once the issue occurs

**Comment by pommee** [comment]
@BackedUpBooty Have you taken my comment into consideration? And if so, has the behavior corrected itself?

**Comment by BackedUpBooty** [comment]
Sorry, I only tend to get the weekend to tinker. Originally had directories on a NAS but was getting some strange permission issues, so have used directories on the host machine inside the VM instead. Will let you know how it goes in the next 8-24 hours,

**Comment by pommee** [comment]
> Sorry, I only tend to get the weekend to tinker. Originally had directories on a NAS but was getting some strange permission issues, so have used directories on the host machine inside the VM instead. Will let you know how it goes in the next 8-24 hours,

All good, hoping this solves your issue.

**Comment by BackedUpBooty** [comment]
Update: even with persistent mounted volumes, my instance continues to restart itself and not allow login using the password. 

Current docker log file which is from approx 14 hours ago:
![Image](https://github.com/user-attachments/assets/4413e281-9853-46cc-873a-c9fc11be7da7)

Current command output as per 

> You can run something like this to get the password:

![Image](https://github.com/user-attachments/assets/2d0fb095-a5f7-42b2-a633-f15fb207fb08)

**Comment by pommee** [comment]
sqlite3 is separate from GoAway and can be found at their website https://www.sqlite.org/download.html.

**Comment by BackedUpBooty** [comment]
OK so the password has been hashed. Beginning of it looks like

`$2a$10$0v7hRh0tn85uw7Gqi`

**Comment by pommee** [comment]
This is a tough nut to crack, everything checks out and not something I have encountered before (neither has it been reported previously). I think our best bet (sadly) is to wait this one out as of now and I will spend some time in the future digging into this some more.  

Fully understand if you don't have the time nor interest to spend more time on this and thanks for the help.

**Comment by BackedUpBooty** [comment]
Am happy to help test if there's something else for me to test, or try and find more info for you in logs, no problem at all.

**Comment by pommee** [comment]
@BackedUpBooty There was recently a large overhaul of the database layer, so I am interested to see if this issue has persisted for you?  

Please update to the latest version and verify.  
In the case of this still being present, provide some logs.

**Comment by BackedUpBooty** [comment]
@pommee sure i'll give it another go, let me come back to you in a day or two

@pommee Edit: so far so good, no issues in not being able to log back in after 8 hours or so. But FYI getting this error when adding lists from the recommended (although the list in question is actually added):

```
[0.114ms] [rows:0] INSERT INTO `sources` (`name`,`url`,`active`,`last_updated`) VALUES ("Gambling","https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts",true,1758964390) ON CONFLICT (`name`,`url`) DO NOTHING RETURNING `id`
2025/09/27 09:14:41 [ERROR] Failed to add source: failed to insert source: SQL logic error: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint (1)
[0.119ms] [rows:0] INSERT INTO `sources` (`name`,`url`,`active`,`last_updated`) VALUES ("Unified hosts + fakenews + gambling + porn","https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts",true,1758964481) ON CONFLICT (`name`,`url`) DO NOTHING RETURNING `id`
2025/09/27 09:14:41 goaway/backend/dns/lists/blacklist.go:762 SQL logic error: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint (1)
[326.489ms] [rows:592727] SELECT DISTINCT `domain` FROM `blacklists`
2025/09/27 09:14:41 goaway/backend/dns/lists/blacklist.go:327 SLOW SQL >= 200ms
[429.485ms] [rows:0] SELECT * FROM `notifications` WHERE read = true
2025/09/27 09:14:40 goaway/backend/notifications/notifications.go:67 SLOW SQL >= 200ms
2025/09/27 09:14:40 [INFO] Added 165779 domains from list 'Unified hosts + fakenews + gambling + porn' with url 'https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts'
```

Final thing (not sure if this is covered in another ticket) but the Clients page is somewhat non-functional. All clients are listed as 'unknown' and not clickable:

<img width="1500" height="833" alt="Image" src="https://github.com/user-attachments/assets/52abb0af-5754-4877-becc-eaa2be403ad7" />

**Comment by pommee** [comment]
@BackedUpBooty Thanks for reporting back.  

The addition of a new list issue has been fixed in [v0.62.5](https://github.com/pommee/goaway/releases/tag/v0.62.5).  

In the latest version, I have it set to where if the hostname is unknown, it will instead show the client IP. Hopefully this also fixes the issue where you can't open the client details.

**Comment by pommee** [comment]
@BackedUpBooty Did the newest version solve the "clients map" issue and addition of new lists for you?

If solved, please close the issue.

**Comment by BackedUpBooty** [comment]
@pommee sorry thought I'd replied. So the IPs display which is helpful, however there's no further detail / still not getting anything when clicking. Tbh I only tried in chrome, would another browser change this maybe?

**Comment by pommee** [comment]
Browser should not make a difference. I do all my testing via Chrome, however I have encoutered issues with Zen.

A request @BackedUpBooty ...  
While clicking one of the client nodes, could you please have the 'developer console' open in chrome. And also have the network tab open to see if any requests are reporting a failure?

**Comment by BackedUpBooty** [comment]
The nodes aren't actually clickable so I wouldn't expect to see that it would register anything for them, but there's an interesting 'pending' for the websocket protocol switch - handshake accepted but looks like it stalled somewhere. All other lines in the network console are alternating server and notifications with code 200.

<img width="1569" height="814" alt="Image" src="https://github.com/user-attachments/assets/544a95f8-cf9e-45f7-9028-276874d19c40" />

I'm not seeing anything in the container logs, there's a vacuuming database error which repeats every 5 minutes, but don't think that's relevant here. 

<img width="663" height="310" alt="Image" src="https://github.com/user-attachments/assets/a4cc381d-dc21-4042-830e-548ee3facf20" />

**Comment by pommee** [comment]
This could be a database issue. After you updated, did you remove your previous database files?

**Comment by BackedUpBooty** [comment]
This is a fresh install without importing any database, so all is from scratch.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by pommee** [comment]
@BackedUpBooty Please do me a favor. I am currently trying to clean out the issues reported (saving me and others time), i.e closing this ticket as it has also mutated over time. If anything is still an issue, please open a new issue.
